name: lacto_view_server
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

# As chaves 'environment', 'dependencies', 'dev_dependencies'
# estão agora em ordem alfabética abaixo.

dependencies:
  dart_frog: ^1.0.0
  dart_firebase_admin: ^0.4.1

dev_dependencies:
  dart_frog_lint: ^0.1.0
  melos: ^6.1.0
  mocktail: ^1.0.3
  test: ^1.25.5

environment:
  sdk: ">=3.0.0 <4.0.0"